# Generated by Django 4.2.10 on 2024-02-12 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='user_response',
            field=models.TextField(default='Sample Text'),
            preserve_default=False,
        ),
    ]
